---
title: "EDS 215 Day 5 Notes"
author: "Scout Leonard"
date: "9/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Stuff that sounds important! 

- A class of statements called **alter** that allow you to change things in the schema. 
- `dbExectute()` sends instructions to the database that do not use tables 
-

**Commond** + **shift** + **C** comments out a bunch of code at once! 

#### Bash commands: 

- `cut`: 
- `uniq` shows the lines that are unique
- `uniq -d` shows the lines that ~aren't unique~ 
  - you have to `sort` first and then pipe into `uniq` command 
  - `sort` goes through observations in order 
  - `sort -u` is a faster way of saying `sort | uniq` 
  - `uniq -c` give a count of how many unique values encountered 
- `>file_name` stores your results as a file with the given name
- `time(commandline)`: tells you how long it takes to run the command 
- `^C` stops the program, but some chucks may still run if they are incomplete
- `cat` grabs one file at a time and spits it out into your terminal
  - `cat` versus `echo`? 

You can talk to R  through the command line.

When you run commands on sorted files, they are really fast. 


**FIPS** code is an unambiguous identifier for U.S, states. There are FIPS codes for counties, as well. 

Codes are wonky for data scientist because they are treated as numbers when they are symbolic and not meant to be manipulated. It's a bad idea to use codes that are numbers for new schemes!

ctrl +d -> end of file editor 

### dbplyr

**dbplyr** is an R to SQL translater. 



